name: Checks

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt,clippy --target wasm32-unknown-unknown
          rustup default stable
      - uses: Swatinem/rust-cache@v2
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Lints
        run: cargo clippy --all-targets --locked -- -D warnings
      - name: Tests
        run: cargo test --locked
      - name: WebAssembly check
        run: cargo check --locked --target wasm32-unknown-unknown
