name : Deploy to Cloudflare Pages
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install Trunk
        run: cargo install trunk
      - name: Build
        run: trunk build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=spectre --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
